# Generated by Django 4.2.6 on 2024-01-18 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('level', models.IntegerField(blank=True, choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], null=True, verbose_name='Уровень')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('debt_to_supplier', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Задолженность перед поставщиком')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('country', models.CharField(blank=True, max_length=250, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=250, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=250, null=True, verbose_name='Улица')),
                ('house_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер дома')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading_network.link', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Элемент торговой сети',
                'verbose_name_plural': 'Элементы торговой сети',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('model', models.CharField(blank=True, max_length=150, null=True, verbose_name='Модель')),
                ('release_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата выхода')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='цена')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_network.link', verbose_name='торговая сеть')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
